// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com.smoc.cloud.filters.grpc/filters.proto

package com.smoc.cloud.filters.grpc.lib.filter;

public interface FilterRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:FilterRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string phone = 1;</code>
   * @return The phone.
   */
  java.lang.String getPhone();
  /**
   * <code>string phone = 1;</code>
   * @return The bytes for phone.
   */
  com.google.protobuf.ByteString
      getPhoneBytes();

  /**
   * <code>string account = 2;</code>
   * @return The account.
   */
  java.lang.String getAccount();
  /**
   * <code>string account = 2;</code>
   * @return The bytes for account.
   */
  com.google.protobuf.ByteString
      getAccountBytes();

  /**
   * <code>string message = 3;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 3;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>string templateId = 4;</code>
   * @return The templateId.
   */
  java.lang.String getTemplateId();
  /**
   * <code>string templateId = 4;</code>
   * @return The bytes for templateId.
   */
  com.google.protobuf.ByteString
      getTemplateIdBytes();

  /**
   * <code>string carrier = 5;</code>
   * @return The carrier.
   */
  java.lang.String getCarrier();
  /**
   * <code>string carrier = 5;</code>
   * @return The bytes for carrier.
   */
  com.google.protobuf.ByteString
      getCarrierBytes();

  /**
   * <code>string provinceCode = 6;</code>
   * @return The provinceCode.
   */
  java.lang.String getProvinceCode();
  /**
   * <code>string provinceCode = 6;</code>
   * @return The bytes for provinceCode.
   */
  com.google.protobuf.ByteString
      getProvinceCodeBytes();

  /**
   * <code>string channelId = 7;</code>
   * @return The channelId.
   */
  java.lang.String getChannelId();
  /**
   * <code>string channelId = 7;</code>
   * @return The bytes for channelId.
   */
  com.google.protobuf.ByteString
      getChannelIdBytes();
}
