// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com.smoc.cloud.filters.grpc/filters.proto

package com.smoc.cloud.filters.grpc.lib.filter;

public interface FilterResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:FilterResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string code = 1;</code>
   * @return The code.
   */
  java.lang.String getCode();
  /**
   * <code>string code = 1;</code>
   * @return The bytes for code.
   */
  com.google.protobuf.ByteString
      getCodeBytes();

  /**
   * <code>string message = 2;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
