// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com.smoc.cloud.filters.grpc/filters.proto

package com.smoc.cloud.filters.grpc.lib.filter;

public final class FullFilterProto {
  private FullFilterProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FilterRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FilterRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FilterResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FilterResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n)com.smoc.cloud.filters.grpc/filters.pr" +
      "oto\"\216\001\n\rFilterRequest\022\r\n\005phone\030\001 \001(\t\022\017\n\007" +
      "account\030\002 \001(\t\022\017\n\007message\030\003 \001(\t\022\022\n\ntempla" +
      "teId\030\004 \001(\t\022\017\n\007carrier\030\005 \001(\t\022\024\n\014provinceC" +
      "ode\030\006 \001(\t\022\021\n\tchannelId\030\007 \001(\t\"/\n\016FilterRe" +
      "sponse\022\014\n\004code\030\001 \001(\t\022\017\n\007message\030\002 \001(\t2<\n" +
      "\rFilterService\022+\n\006Filter\022\016.FilterRequest" +
      "\032\017.FilterResponse\"\000B;\n&com.smoc.cloud.fi" +
      "lters.grpc.lib.filterB\017FullFilterProtoP\001" +
      "b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_FilterRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_FilterRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FilterRequest_descriptor,
        new java.lang.String[] { "Phone", "Account", "Message", "TemplateId", "Carrier", "ProvinceCode", "ChannelId", });
    internal_static_FilterResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_FilterResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FilterResponse_descriptor,
        new java.lang.String[] { "Code", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
